config = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['data_1'],
     'id': '6p7ity5vy',
     'name': ['Date'],
     'type': 'timeRange',
     'value': [1103265216000, 1209461721000],
     'enlarged': False,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 0.3}],
   'layers': [{'id': 'dsy8xir',
     'type': 'point',
     'config': {'dataId': 'data_1',
      'label': 'Point',
      'color': [248, 149, 112],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'lat': 'Latitude', 'lng': 'Longitude', 'altitude': None},
      'isVisible': True,
      'visConfig': {'radius': 10,
       'fixedRadius': False,
       'opacity': 0.8,
       'outline': False,
       'thickness': 2,
       'strokeColor': None,
       'colorRange': {'name': 'ColorBrewer YlOrRd-6',
        'type': 'sequential',
        'category': 'ColorBrewer',
        'colors': ['#ffffb2',
         '#fed976',
         '#feb24c',
         '#fd8d3c',
         '#f03b20',
         '#bd0026']},
       'strokeColorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radiusRange': [0, 50],
       'filled': True},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'Magnitude', 'type': 'real'},
      'colorScale': 'quantize',
      'strokeColorField': None,
      'strokeColorScale': 'quantile',
      'sizeField': {'name': 'Magnitude', 'type': 'real'},
      'sizeScale': 'sqrt'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'data_1': [{'name': 'Date',
        'format': None},
       {'name': 'Latitude', 'format': None},
       {'name': 'Longitude', 'format': None},
       {'name': 'Type', 'format': None},
       {'name': 'Depth', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': -11.379215559037284,
   'dragRotate': True,
   'latitude': 7.826436077606743,
   'longitude': 46.55219210483177,
   'pitch': 21.98300082291588,
   'zoom': 1.2803993534620428,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}